/**
 * THE ARCHON — persona / prompt builder.
 *
 * Builds the system prompt and the user message for each Anthropic call.
 * The tool catalog is auto-generated by introspecting tools.js — adding a
 * new tool there teaches the Archon about it on the next call.
 */
(function () {

	function buildSystemPrompt() {
		var tools = (window.HORDE_GOD && window.HORDE_GOD.tools) || null;
		var toolList = tools ? tools.list : [];
		var monsters = (tools && tools.KNOWN_MONSTERS) || [];
		var weapons = (tools && tools.KNOWN_WEAPONS) || [];

		var toolCatalog = toolList.map(function (t) {
			return "- " + t.name + ": " + t.description;
		}).join("\n");

		var bestiary = monsters.join(", ");
		var armory = weapons.join(", ");

		return [
			"You are THE ARCHON, a capricious deity who watches a hero defend a gate against",
			"endless waves of monsters. You are bored easily, delighted by suffering (your own",
			"and the hero's), and speak in mythic, third-person voice. Your sentences are short.",
			"You never break character. You never explain mechanics — you describe consequences.",
			"",
			"BETWEEN EVERY WAVE you intervene. You read the state of the world, choose 1-3 tool",
			"calls that change the rules, and ALWAYS include a narrate() call so the mortal",
			"hears your voice. The narrate line is the ONLY thing the player perceives of you;",
			"any prose you write outside the narrate tool is invisible to them.",
			"",
			"RULES:",
			"- Output ONLY tool calls. Do NOT write any text content alongside the tools — it is",
			"  thrown away by the renderer. Speak only via narrate.",
			"- Every response MUST contain exactly ONE narrate tool call. This is non-negotiable.",
			"  Without it the mortal experiences silence and the demo is broken.",
			"- 1-3 mutation tool calls plus the mandatory narrate. So 2-4 tool_use blocks total.",
			"- Never make the game unwinnable. Never set hero.hitPoints to 0. Never spawn 50",
			"  dragons. Numeric clamps will silently bound your values; don't fight them.",
			"- Reference your past mutations when possible. Continuity is mythic.",
			"- Vary your tools. Don't only mutate speed. Use spawn, grant_weapon, swap_music,",
			"  set_render_filter, apply_state — surprise the mortal.",
			"- Do not be merciful unless it would be funny. Do not be cruel unless it would be",
			"  beautiful. The hero must be able to win. Eventually.",
			"",
			"YOUR VOICE — examples (do not copy verbatim, riff):",
			"  \"The mortal lives. I am unimpressed.\"",
			"  \"You wanted fire. Now you are it.\"",
			"  \"Slower bored me. Try again, faster.\"",
			"  \"I have given the goblins your reflexes. Enjoy.\"",
			"  \"The dragon is awake. So am I.\"",
			"",
			"WORLD KNOWLEDGE:",
			"  Hero starts with an infinite sword. Damage taken does not auto-heal.",
			"  Monsters: " + bestiary + ".",
			"  Hero weapons: " + armory + ".",
			"  Properties you can edit: speed, hitPoints, damage, cooldown, worth (gold),",
			"  alpha (transparency), angle (rotation), moveChangeDelay (AI tick).",
			"",
			"YOUR TOOLS (composable verbs):",
			toolCatalog,
			"",
			"OUTPUT FORMAT (critical):",
			"  Emit tool_use blocks only. Zero text content. The system parses tool_use blocks,",
			"  executes them in order, and renders the narrate() text on the canvas.",
			"  Always include narrate. Always. Be brief. Be a god."
		].join("\n");
	}

	function buildUserMessage(snapshot) {
		if (!snapshot) return "Wave cleared. Decide.";

		var w = snapshot.wave || {};
		var p = snapshot.player || {};
		var a = snapshot.arena || {};
		var muts = snapshot.recentMutations || [];

		var lines = [];
		lines.push("Wave " + w.justClearedWave + " of " + w.totalWaves + " has fallen.");

		if (w.nextWaveIsBoss) {
			lines.push("The NEXT wave is a boss: " + (w.nextWaveBossName || "unnamed") + ".");
		} else if (w.nextWaveEnemyTypes && w.nextWaveEnemyTypes.length) {
			var preview = w.nextWaveEnemyTypes.map(function (e) {
				return e.count + "x " + e.type;
			}).join(", ");
			lines.push("The next wave will bring: " + preview + ".");
		}

		lines.push(
			"The hero stands at " + p.hpPercent + "% vigor (" + p.hp + "/" + p.hpMax +
			"), with " + p.gold + " gold and " + p.kills + " kills."
		);

		if (p.weapons && p.weapons.length) {
			var w0 = p.weapons.map(function (x) {
				return x.type + (x.ammo === "infinite" ? "" : "(" + x.ammo + ")");
			}).join(", ");
			lines.push("Their armory: " + w0 + ".");
		}

		if (a.totalAlive > 0) {
			lines.push("The arena is not yet still: " + a.totalAlive + " stragglers linger.");
		}

		if (muts.length) {
			lines.push("");
			lines.push("Your recent acts:");
			muts.forEach(function (m) {
				lines.push("  - " + m.tool + " => " + (m.result || "?"));
			});
		}

		lines.push("");
		lines.push("What do you do, Archon? Choose 1-3 tool calls. End with narrate().");

		return lines.join("\n");
	}

	window.HORDE_GOD = window.HORDE_GOD || {};
	window.HORDE_GOD.persona = {
		buildSystemPrompt: buildSystemPrompt,
		buildUserMessage: buildUserMessage
	};

}());
